spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  profiles:
    active: rabbit
